---
title: "Data Analysis"
author: "Christian Hobelsberger"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
install.packages(c("glmnet", "sjPlot"))
library(glmnet)
library(sjPlot)
```

### Setup for modelling
```{r include=FALSE}
micro_restr <- readRDS("data/protected_data/micro_restr.RDS")
micro_restr$anxious <- ifelse(micro_restr$D1 %in% levels(micro_restr$D1)[4:5], 
                              TRUE,
                              ifelse(is.na(micro_restr$D1), NA, FALSE))
micro_restr$depressed <- ifelse(micro_restr$D2 %in% levels(micro_restr$D1)[4:5], 
                                TRUE, 
                                ifelse(is.na(micro_restr$D2), NA, FALSE))
```

# Microdata and restriction data logistic regression model
```{r Full logistic regression}
# Set reference categories
micro_restr$E4 <- relevel(micro_restr$E4, ref = "45-54")
micro_restr$E3 <- relevel(micro_restr$E3, ref = "Male")
micro_restr$E8 <- relevel(micro_restr$E8, ref = "Secondary school complete")
micro_restr$E2 <- relevel(micro_restr$E2, ref = "Town")
micro_restr$D10 <- relevel(micro_restr$D10, ref = "Other")
micro_restr$B0 <- relevel(micro_restr$B0, ref = "No")
micro_restr$G1 <- relevel(micro_restr$G1, ref = "A little")
micro_restr$D7a <- relevel(micro_restr$D7a, ref = "No")

# Rename indicies
micro_restr <- micro_restr %>%
  rename(General_containment_measures_index = bl_mn_idx_t,
         Secondary_schools_measures_index = bl_mn_idx_t_m02a,
         Elementary_schools_measures_index = bl_mn_idx_t_m02b,
         Daycare_centers_measures_index = bl_mn_idx_t_m03,
         Mask_obligation_index = bl_mn_idx_t_m16)

# Fit model

# E4 = Age, E3 = Gender, E8 = Education, E2 = Where do you live?, E5 = Number people slept in same place
# E7a = Number rooms used for sleeping, D7a = Paid work
# NOT INCLUDED: D10 = Field of business, B0 = Had Covid?, G1 = Worried catching Covid?, J1 = Number children in houshold

model_glm_restr_D1 <- glm(anxious ~ General_containment_measures_index + Secondary_schools_measures_index + 
                            Elementary_schools_measures_index + Daycare_centers_measures_index + 
                            Mask_obligation_index + E4 + E3 + E8 + E2 + E5 + D7a + E7a,
                          family=binomial(link='logit'), data=micro_restr)
summary(model_glm_restr_D1)
exp(model_glm_restr_D1$coefficients)

model_glm_restr_D2 <- glm(depressed ~ General_containment_measures_index + Secondary_schools_measures_index + 
                            Elementary_schools_measures_index + Daycare_centers_measures_index + 
                            Mask_obligation_index + E4 + E3 + E8 + E2 + E5 + D7a + E7a,
                          family=binomial(link='logit'), data=micro_restr)
summary(model_glm_restr_D2)
exp(model_glm_restr_D2$coefficients)

sink("Plots/models/model_glm_restr_D1.txt")
print(summary(model_glm_restr_D1))
sink()

sink("Plots/models/model_glm_restr_D2.txt")
print(summary(model_glm_restr_D2))
sink()


# Forestplots
plot_model(model_glm_restr_D1, ci_method = "wald")
ggsave("Plots/models/model_glm_restr_D1.png", width = 12, height = 9)

plot_model(model_glm_restr_D2, ci_method = "wald")
ggsave("Plots/models/model_glm_restr_D2.png", width = 12, height = 9)

## NO LOG-TRANSFORMATION

# Create list of models and transform coefficients so x-axis is not log-transformed
all.models <- list()
all.models[[1]] <- model_glm_restr_D1
all.models[[1]]$coefficients <- exp(all.models[[1]]$coefficients)
all.models[[2]] <- model_glm_restr_D2
all.models[[2]]$coefficients <- exp(all.models[[2]]$coefficients)

# transform = NULL because coefficients are already exp() and x-axis should not be log-transformed
plot_models(all.models, m.labels = c("anxious (D1)", "depressed (D2)"), transform = NULL, prefix.labels = "varname", grid.breaks = c(0,1,2,3,4,5)) +
  theme(text = element_text(size = 15)) +
  geom_hline(yintercept = 1, linetype = "dashed", alpha = .375)
ggsave("Plots/models/model_glm_restr_D1_D2.png", width = 12, height = 12)
ggsave("Plots/paper/model_glm_restr_D1_D2.png", width = 14, height = 14)

## LOG-TRANSFORMATION

# Create list of models
all.models_log <- list()
all.models_log[[1]] <- model_glm_restr_D1
all.models_log[[2]] <- model_glm_restr_D2

# transform = NULL because coefficients are already exp() and x-axis should not be log-transformed
plot_models(all.models_log, m.labels = c("anxious (D1)", "depressed (D2)"))
ggsave("Plots/models/model_glm_restr_D1_D2_log_scale.png", width = 12, height = 9)

# Checking the fit

# Generate predicted probabilities for a range of values of the categorical predictors
pred_data <- expand.grid(E4 = levels(micro_restr$E4), E3 = levels(micro_restr$E3), E8 = levels(micro_restr$E8), E2 = levels(micro_restr$E2), D7a = levels(micro_restr$D7a))
pred_data$pred_prob <- predict(model_glm_restr_D1, newdata = pred_data, type = "response")

# Add observed outcome to predicted data
pred_data$anxious <- micro_restr$anxious[match(paste(micro_restr$E4, micro_restr$E3, micro_restr$E8, micro_restr$E2, micro_restr$D7a), paste(pred_data$E4, pred_data$E3, pred_data$E8, pred_data$E2, pred_data$D7a))]

# Create plot
ggplot(pred_data, aes(x = pred_prob, y = anxious, color = E4, shape = E3)) +
  geom_point() +
  facet_wrap(~ E2 + D7a + E8, ncol = 3, scales = "free") +
  labs(x = "Predicted probability", y = "Observed outcome")
```