---
title: "Data Analysis"
author: "Christian Hobelsberger"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
# install.packages(c("kableExtra", "flextable", "ggpubr"))
library(gridExtra)
library(ggpubr)
library(tidyverse)
theme_set(theme_bw())

# Read tables from data_analysis_prep_tables.R
table_Obs_D1_Date <- readRDS(file = "tables/analysis/table_Obs_D1_Date.RDS")
table_NA_D1_Date <- readRDS(file = "tables/analysis/table_NA_D1_Date.RDS")
table_Obs_D2_Date <- readRDS(file = "tables/analysis/table_Obs_D2_Date.RDS")
table_NA_D2_Date <- readRDS(file = "tables/analysis/table_NA_D2_Date.RDS")
table_Obs_D4_Date <- readRDS(file = "tables/analysis/table_Obs_D4_Date.RDS")
table_NA_D4_Date <- readRDS(file = "tables/analysis/table_NA_D4_Date.RDS")
table_Obs_D5_Date <- readRDS(file = "tables/analysis/table_Obs_D5_Date.RDS")
table_NA_D5_Date <- readRDS(file = "tables/analysis/table_NA_D5_Date.RDS")
table_Obs_region_agg_Date_weekly <- readRDS(file = "tables/analysis/table_Obs_region_agg_Date_weekly.RDS")
table_D1_weekday <- readRDS(file = "tables/analysis/table_D1_weekday.RDS")
table_D1_weekday_per_D1 <- readRDS(file = "tables/analysis/table_D1_weekday_per_D1.RDS")
table_D1_Date <- readRDS(file = "tables/analysis/table_D1_Date.RDS")
table_D2_weekday <- readRDS(file = "tables/analysis/table_D2_weekday.RDS")
table_D2_weekday_per_D2 <- readRDS(file = "tables/analysis/table_D2_weekday_per_D2.RDS")


# Function to plot count, mean in boxplot; source:
# https://gscheithauer.medium.com/how-to-add-number-of-observations-to-a-ggplot2-boxplot-b22710f7ef80
stat_box_data <- function(x, upper_limit = 75) {
    return( 
        data.frame(
            y = 0.95 * upper_limit,
            label = paste('count =', 
                          format(length(x), big.mark = ",", decimal.mark = ".", scientific = FALSE), 
                          '\n',
                          'mean =', 
                          format(round(mean(x), 1), big.mark = ",", decimal.mark = ".", scientific = FALSE))
        )
    )
}
stat_box_data_80 <- function(x, upper_limit = 80) {
    return( 
        data.frame(
            y = 0.95 * upper_limit,
            label = paste('count =', 
                          format(length(x), big.mark = ",", decimal.mark = ".", scientific = FALSE), 
                          '\n',
                          'mean =', 
                          format(round(mean(x), 1), big.mark = ",", decimal.mark = ".", scientific = FALSE))
        )
    )
}
stat_box_data_115 <- function(x, upper_limit = 115) {
    return( 
        data.frame(
            y = 0.95 * upper_limit,
            label = paste('count =', 
                          format(length(x), big.mark = ",", decimal.mark = ".", scientific = FALSE), 
                          '\n',
                          'mean =', 
                          format(round(mean(x), 1), big.mark = ",", decimal.mark = ".", scientific = FALSE))
        )
    )
}
```

## Analysis of Corona data from Germany

```{r Analysis of Corona data from Germany}
bl_massnahmen_index_tag <- readRDS(file = "data/protected_data/bl_massnahmen_index_tag.RDS")

# Plot: German restriction index over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t, color = bundesland)) +
  geom_line(alpha = .5) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German measures index over time by federal states",
       x = "Date",
       y = "Measures index federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_date.png", width = 12, height = 9)
  

# Plot: German restriction index over time for Bavaria 
ggplot(data = filter(bl_massnahmen_index_tag, bundesland == "Bayern"), 
       mapping = aes(x = datum, y = bl_mn_idx_t)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  geom_line()  +
  labs(title = "German measures index over time for Bavaria",
       x = "Date",
       y = "Measures index federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_date_bavaria.png", width = 12, height = 9)

# Plot: German restriction index (Daycare centers) over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t_m03, color = bundesland)) +
  geom_line(alpha = .5) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German measures index (Daycare centers) over time by federal states",
       x = "Date",
       y = "Measures index (Daycare centers) federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_daycare_date.png", width = 12, height = 9)

# Plot: German restriction index (Secondary schools) over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t_m02a, color = bundesland)) +
  geom_line(alpha = .5) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German measures index (Secondary schools) over time by federal states",
       x = "Date",
       y = "Measures index (Secondary schools) federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_sec_schools_date.png", width = 12, height = 9)

# Plot: German restriction index (Elementary schools) over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t_m02b, color = bundesland)) +
  geom_line(alpha = .5) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German measures index (Elementary schools) over time by federal states",
       x = "Date",
       y = "Measures index (Elementary schools) federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_elem_schools_date.png", width = 12, height = 9)

# Plot: German restriction index (Mask obligation) over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t_m16, color = bundesland)) +
  geom_line(alpha = .5) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German measures index (Mask obligation) over time by federal states",
       x = "Date",
       y = "Measures index (Mask obligation) federal states per day (in %)")
ggsave(filename = "Plots/german_restrictions/measures_maks_date.png", width = 12, height = 9)
```

## Analysis of macrodata with restriction data

```{r Analysis of macrodata with restriction data}
# Read macrodata with restriction data
macro_restr <- readRDS(file = "data/protected_data/macro_restr.RDS")

# Plot: German restriction index vs. anxious_7d
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = anxious_7d)) +
  geom_point(alpha = .1) +
  labs(title = "German restriction index vs. anxious_7d",
       x = "Measures index federal states per day (in %)",
       y = "anxious_7d")
ggsave(filename = "Plots/macro_restrictions/measures_anxious7d.png", width = 12, height = 9)

# Plot: German restriction index vs. depressed_7d
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = depressed_7d)) +
  geom_point(alpha = .1) +
  labs(title = "German restriction index vs. depressed_7d",
       x = "Measures index federal states per day (in %)",
       y = "depressed_7d")
ggsave(filename = "Plots/macro_restrictions/measures_depressed_7d.png", width = 12, height = 9)

# Plot: German restriction index vs. depressed_7d SMOOTHED
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = depressed_7d)) +
  geom_point(alpha = .1) +
  geom_smooth() +
  labs(title = "German restriction index vs. depressed_7d",
       x = "Measures index federal states per day (in %)",
       y = "depressed_7d")
ggsave(filename = "Plots/macro_restrictions/measures_depressed_7d_smoothed.png", width = 12, height = 9)

# Plot: German restriction index vs. worried_become_ill
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = worried_become_ill)) +
  geom_point(alpha = .1) +
  labs(title = "German restriction index vs. worried_become_ill",
       x = "Measures index federal states per day (in %)",
       y = "worried_become_ill")
ggsave(filename = "Plots/macro_restrictions/measures_worried_become_ill.png", width = 12, height = 9)

# Plot: German restriction index vs. finance
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = finance)) +
  geom_point(alpha = .1) +
  labs(title = "German restriction index vs. finance",
       x = "Measures index federal states per day (in %)",
       y = "finance")
ggsave(filename = "Plots/macro_restrictions/measures_finance.png", width = 12, height = 9)

# Plot: German restriction index vs. food_security
ggplot(data = macro_restr, mapping = aes(x = bl_mn_idx_t, y = food_security)) +
  geom_point(alpha = .1) +
  labs(title = "German restriction index vs. food_security",
       x = "Measures index federal states per day (in %)",
       y = "food_security")
ggsave(filename = "Plots/macro_restrictions/food_security.png", width = 12, height = 9)

```

# Analysis of microdata
```{r general analysis of microdata}
# Read in microdata
CTIS_microdata <- readRDS(file = "data/protected_data/CTIS_microdata.RDS")


# Testing -----------------------------------------------------------------------------------------------------

# Spearman rank correlation coefficient of D1, D2: 0.6060078
cor(as.numeric(CTIS_microdata$D1), as.numeric(CTIS_microdata$D2), use="pairwise.complete.obs", method = "spearman")

# Chi-square test of independence
chisq.test(table(CTIS_microdata$D1, CTIS_microdata$D2))

# # Save the crosstable of D1 and D2 as a latex code
# cross_table_D1_D2 <- table(CTIS_microdata$D1, CTIS_microdata$D2)
# 
# knitr::kable(x = cross_table_D1_D2, format = "latex") %>%
#   kableExtra::add_header_above(c("D1 (anxious)" = 1, "D2 (depressed)" = 5))


# Plots with table data: 

# Plot Observations and NAs ----------------------------------------------------------------------------------

# Plot: Observations D1 (anxious) over time
ggplot(data = table_Obs_D1_Date, mapping = aes(x = RecordedDate, y = count)) +
  geom_line() +
  labs(title = "Observations D1 (anxious) over time",
       x = "Date",
       y = "Number of Observations - D1 (per day)")
ggsave("Plots/microdata/Obs_RecordedDate_D1_lineplot.png", width = 12, height = 6)

# Plot: Observations D2 (depressed) over time
ggplot(data = table_Obs_D2_Date, mapping = aes(x = RecordedDate, y = count)) +
  geom_line() +
  labs(title = "Observations D2 (depressed) over time",
       x = "Date",
       y = "Number of Observations - D2 (per day)")
ggsave("Plots/microdata/Obs_RecordedDate_D2_lineplot.png", width = 12, height = 6)

# Plot: Weekly observations of region_agg (federal state) over time
ggplot(data = table_Obs_region_agg_Date_weekly, mapping = aes(x = Date, y = count, color = region_agg)) +
  geom_line() +
  labs(title = "Weekly observations of region_agg (federal state) over time",
       x = "Date",
       y = "Number of weekly observations - region_agg (federal state)") +
  guides(color=guide_legend(title="region_agg (federal state)"))
ggsave("Plots/microdata/Obs_Date_region_agg_weekly_lineplot.png", width = 12, height = 6)

# D1 --------------------------------------------------------------------------------------------------------

# Plot: D1 (anxious) vs. weekdays - abs
ggplot(data = table_D1_weekday, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Observations D1 (anxious) per weekdays", 
       x = "Day of the week",
       y = "Number of observations")
ggsave("Plots/microdata/D1_vs_weekday_abs.png", width = 12, height = 6)

# Plot: D1 (anxious) vs. weekdays - rel
ggplot(data = table_D1_weekday, mapping = aes(x = day_of_week, y = perc)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D1 (anxious) per weekday", 
       x = "Day of the week",
       y = "Relative frequency")
ggsave("Plots/microdata/D1_vs_weekday_rel.png", width = 12, height = 6)

# Plot: D1 (anxious) category vs. weekdays - abs
ggplot(data = table_D1_weekday_per_D1, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(mapping = aes(fill = D1), position = "dodge", stat = "identity") +
  labs(title = "Number of observations per D1 (anxious) category per weekday", 
       x = "Day of the week",
       y = "Number of observations") + 
  scale_fill_brewer(palette = "Blues", name = "D1 (anxious)")
ggsave("Plots/microdata/D1_vs_weekday_category_abs.png", width = 12, height = 6)

# Plot: D1 (anxious) category vs. weekdays - rel
ggplot(data = table_D1_weekday_per_D1, mapping = aes(x = day_of_week, y = perc)) +
  geom_bar(mapping = aes(fill = D1), position = "dodge", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D1 (anxious) categories observed per weekday", 
       x = "Day of the week",
       y = "Relative frequency") + 
  scale_fill_brewer(palette = "Blues", name = "D1 (anxious)")
ggsave("Plots/microdata/D1_vs_weekday_category_rel.png", width = 12, height = 6)

# Plot D1 (anxious) vs RecordedDate
ggplot(data = table_D1_Date, mapping = aes(x = RecordedDate, y = perc)) +
  geom_line(mapping = aes(color = D1)) +
  labs(title = "Relative frequencies of anxious variable over time",
       x = "Date", 
       y = "Relative frequencies",
       color = "D1 (anxious)")
ggsave("Plots/microdata/D1_vs_RecordedDate_lineplot.png", width = 12, height = 6)


# D2 --------------------------------------------------------------------------------------------------------

# Plot: D2 (depressed) vs. weekdays - abs
ggplot(data = table_D2_weekday, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Observations D2 (depressed) per weekdays", 
       x = "Day of the week",
       y = "Number of observations")
ggsave("Plots/microdata/D2_vs_weekday_abs.png", width = 12, height = 6)

# Plot: D2 (depressed) vs. weekdays - rel
ggplot(data = table_D2_weekday, mapping = aes(x = day_of_week, y = perc)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D2 (depressed) per weekday", 
       x = "Day of the week",
       y = "Relative frequency")
ggsave("Plots/microdata/D2_vs_weekday_rel.png", width = 12, height = 6)

# Plot: D2 (depressed) category vs. weekdays - abs
ggplot(data = table_D2_weekday_per_D2, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(mapping = aes(fill = D2), position = "dodge", stat = "identity") +
  labs(title = "Number of observations per D2 (depressed) category per weekday", 
       x = "Day of the week",
       y = "Number of observations") + 
  scale_fill_brewer(palette = "Blues", name = "D2 (depressed)")
ggsave("Plots/microdata/D2_vs_weekday_category_abs.png", width = 12, height = 6)

# Plot: D2 (depressed) category vs. weekdays - rel
ggplot(data = table_D2_weekday_per_D2, mapping = aes(x = day_of_week, y = perc)) +
  geom_bar(mapping = aes(fill = D2), position = "dodge", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D2 (depressed) categories observed per weekday", 
       x = "Day of the week",
       y = "Relative frequency of D2 (depressed) category") + 
  scale_fill_brewer(palette = "Blues", name = "D2 (depressed)")
ggsave("Plots/microdata/D2_vs_weekday_category_rel.png", width = 12, height = 6)

# Plot D2 (depressed) vs RecordedDate
ggplot(data = table_D2_Date, mapping = aes(x = RecordedDate, y = perc)) +
  geom_line(mapping = aes(color = D2)) +
  labs(title = "Relative frequencies of depressed variable over time",
       x = "Date",
       y = "Relative frequencies",
       color = "D2 (depressed)")
ggsave("Plots/microdata/D2_vs_RecordedDate_lineplot.png", width = 12, height = 6)

# Plots without table data -------------------------------------------------------------------


# Plot: Observations region_agg (federal state)
ggplot(data = CTIS_microdata, mapping = aes(x = region_agg)) +
  geom_bar() +
  coord_flip() +
  labs(title = "Observations region_agg (federal state)",
       x = "Number of Observations",
       y = "federal states")
ggsave("Plots/microdata/Obs_region_agg_barplot.png", width = 12, height = 6)
```

# Analysis of microdata with restriction data
```{r Analysis of microdata with restriction data}
# Read microdata with restriction data
micro_restr <- readRDS(file = "data/protected_data/micro_restr.RDS")

# German restriction index -------------------------------------------------------

## D1 ----------------------------------------------------------------------------

# Plot: D1 vs German restriction index
ggplot(data = micro_restr %>% select(D1, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  geom_boxplot() +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
  labs(title = "D1 (anxious) vs. German restriction index",
       x = "D1 (anxious)",
       y = "Measures index federal states per day (in %)")
ggsave("Plots/micro_restrictions/D1_restr_boxplot.png", width = 12, height = 9)

# Plot: D1 vs German restriction index vs E4
ggplot(data = micro_restr %>% select(D1, E4, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E4)) +
    labs(title = "D1 (anxious) vs. German restriction index vs. age group",
         x = "D1 (anxious)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E4 (age group)")
ggsave("Plots/micro_restrictions/D1_restr_E4_boxplot.png", width = 12, height = 6)

# Plot: D1 vs German restriction index vs E8
ggplot(data = micro_restr %>% select(D1, E8, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E8)) +
    labs(title = "D1 (anxious) vs. German restriction index vs. education-level",
         x = "D1 (anxious)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E8 (education-level)")
ggsave("Plots/micro_restrictions/D1_restr_E8_boxplot.png", width = 12, height = 6)

# Plot: D1 vs German restriction index vs E2
ggplot(data = micro_restr %>% select(D1, E2, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E2)) +
    labs(title = "D1 (anxious) vs. German restriction index vs. area of living",
         x = "D1 (anxious)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "E2 (area of living)")
ggsave("Plots/micro_restrictions/D1_restr_E2_boxplot.png", width = 12, height = 6)

# Plot: D1 vs German restriction index vs E3
ggplot(data = micro_restr %>% select(D1, E3, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E3)) +
    labs(title = "D1 (anxious) vs. German restriction index vs. gender",
         x = "D1 (anxious)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "E3 (gender)")
ggsave("Plots/micro_restrictions/D1_restr_E3_boxplot.png", width = 12, height = 6)

# Plot: D1 vs German restriction index vs D7a
ggplot(data = micro_restr %>% select(D1, D7a, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = D7a)) +
    labs(title = "D1 (anxious) vs. German restriction index vs. paid work",
         x = "D1 (anxious)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "D7a (paid work?)")
ggsave("Plots/micro_restrictions/D1_restr_D7a_boxplot.png", width = 12, height = 6)

### German restriction index (Mask obligation) -------------------------------------------------------

# Plot: D1 vs German restriction index (Mask obligation) vs E4
ggplot(data = micro_restr %>% select(D1, E4, bl_mn_idx_t_m16) %>% drop_na(), 
       mapping = aes(x = D1, y = bl_mn_idx_t_m16)) +
  stat_summary(
    fun.data = stat_box_data_115, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E4)) +
    labs(title = "D1 (anxious) vs. German restriction index (Mask obligation) vs. age group",
         x = "D1 (anxious)",
         y = "Measures index (Mask obligation) federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E4 (age group)")
ggsave("Plots/micro_restrictions/D1_restr_masks_E4_boxplot.png", width = 12, height = 6)


## D2 ----------------------------------------------------------------------------

# Plot: D2 vs German restriction index
ggplot(data = micro_restr %>% select(D2, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  geom_boxplot() +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
  labs(title = "D2 (depressed) vs. German restriction index",
       x = "D2 (depressed)",
       y = "Measures index federal states per day (in %)")
ggsave("Plots/micro_restrictions/D2_restr_boxplot.png", width = 12, height = 9)

# Plot: D2 vs German restriction index vs E4
ggplot(data = micro_restr %>% select(D2, E4, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E4)) +
    labs(title = "D2 (depressed) vs. German restriction index vs. age group",
         x = "D2 (depressed)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E4 (age group)")
ggsave("Plots/micro_restrictions/D2_restr_E4_boxplot.png", width = 12, height = 6)

# Plot: D2 vs German restriction index vs E8
ggplot(data = micro_restr %>% select(D2, E8, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E8)) +
    labs(title = "D2 (depressed) vs. German restriction index vs. education-level",
         x = "D2 (depressed)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E8 (education-level)")
ggsave("Plots/micro_restrictions/D2_restr_E8_boxplot.png", width = 12, height = 6)

# Plot: D2 vs German restriction index vs E2
ggplot(data = micro_restr %>% select(D2, E2, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E2)) +
    labs(title = "D2 (depressed) vs. German restriction index vs. area of living",
         x = "D2 (depressed)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "E2 (area of living)")
ggsave("Plots/micro_restrictions/D2_restr_E2_boxplot.png", width = 12, height = 6)

# Plot: D2 vs German restriction index vs E3
ggplot(data = micro_restr %>% select(D2, E3, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E3)) +
    labs(title = "D2 (depressed) vs. German restriction index vs. gender",
         x = "D2 (depressed)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "E3 (gender)")
ggsave("Plots/micro_restrictions/D2_restr_E3_boxplot.png", width = 12, height = 6)

# Plot: D2 vs German restriction index vs D7a
ggplot(data = micro_restr %>% select(D2, D7a, bl_mn_idx_t) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t)) +
  stat_summary(
    fun.data = stat_box_data, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = D7a)) +
    labs(title = "D2 (depressed) vs. German restriction index vs. paid work",
         x = "D2 (depressed)",
         y = "Measures index federal states per day (in %)") + 
    scale_color_brewer(palette = "Dark2", name = "D7a (paid work?)")
ggsave("Plots/micro_restrictions/D2_restr_D7a_boxplot.png", width = 12, height = 6)

### German restriction index (Mask obligation) -------------------------------------------------------

# Plot: D2 vs German restriction index (Mask obligation) vs E4
ggplot(data = micro_restr %>% select(D2, E4, bl_mn_idx_t_m16) %>% drop_na(), 
       mapping = aes(x = D2, y = bl_mn_idx_t_m16)) +
  stat_summary(
    fun.data = stat_box_data_115, 
    geom = "text", 
    hjust = 0.5,
    vjust = 0.9
  ) +
    geom_boxplot(aes(color = E4)) +
    labs(title = "D2 (depressed) vs. German restriction index (Mask obligation) vs. age group",
         x = "D2 (depressed)",
         y = "Measures index (Mask obligation) federal states per day (in %)") + 
    scale_color_brewer(palette = "Blues", name = "E4 (age group)")
ggsave("Plots/micro_restrictions/D2_restr_masks_E4_boxplot.png", width = 12, height = 6)
```

# Plots for Paper
```{r}
# Read in microdata
CTIS_microdata <- readRDS(file = "data/protected_data/CTIS_microdata.RDS")
# Read microdata with restriction data
micro_restr <- readRDS(file = "data/protected_data/micro_restr.RDS")

# Read gernab restriction data
bl_massnahmen_index_tag <- readRDS(file = "data/protected_data/bl_massnahmen_index_tag.RDS")



# Plot: Observations D1 (anxiety) over time
Obs_RecordedDate_D1_lineplot <- ggplot(data = table_Obs_D1_Date, mapping = aes(x = RecordedDate, y = count)) +
  geom_line() +
  labs(title = "Number of observations D1 (anxiety) over time",
       x = "Date",
       y = "Number of daily observations") +
  ylim(0, 2000) +
  theme(text = element_text(size = 15)) 
# Plot: Observations D2 (depression) over time
Obs_RecordedDate_D2_lineplot <- ggplot(data = table_Obs_D2_Date, mapping = aes(x = RecordedDate, y = count)) +
  geom_line() +
  labs(title = "Number of observations D2 (depression) over time",
       x = "Date",
       y = "Number of daily observations") +
  ylim(0, 2000) +
  theme(text = element_text(size = 15)) 

ggarrange(Obs_RecordedDate_D1_lineplot, Obs_RecordedDate_D2_lineplot, ncol = 1, nrow = 2,
          labels = c("A", "B", "C", "D"))
ggsave("Plots/paper/arranged_RecordedDate_D1_D2.png", width = 12, height = 9)

# Operations
mean(table_Obs_D1_Date$count)
print(table_Obs_D1_Date %>% arrange(desc(count)), n = 20)
print(table_Obs_D1_Date %>% arrange(count), n = 20)

## -----------

# Plot D1 (anxiety) vs RecordedDate
D1_vs_RecordedDate_lineplot <- ggplot(data = table_D1_Date, mapping = aes(x = RecordedDate, y = perc)) +
  geom_line(mapping = aes(color = D1)) +
  labs(title = "Relative frequencies of D1 (anxiety) over time",
       x = "Date", 
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15), axis.text.x = element_text(vjust = 1, hjust = 0.75)) 
# Plot D2 (depression) vs RecordedDate
D2_vs_RecordedDate_lineplot <- ggplot(data = table_D2_Date, mapping = aes(x = RecordedDate, y = perc)) +
  geom_line(mapping = aes(color = D2)) +
  labs(title = "Relative frequencies of D2 (depression) over time",
       x = "Date",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15), axis.text.x = element_text(vjust = 1, hjust = 0.75)) 

ggarrange(D1_vs_RecordedDate_lineplot, D2_vs_RecordedDate_lineplot, ncol = 1, nrow = 2,
          labels = c("A", "B", "C", "D"), common.legend = TRUE, legend = "bottom")
ggsave("Plots/paper/arranged_D1_D2_vs_RecordedDate.png", width = 12, height = 9)

# Operations
table_D1_Date %>% ungroup() %>% group_by(D1) %>% summarise(mean(perc))
table_D2_Date %>% ungroup() %>% group_by(D2) %>% summarise(mean(perc))

## -----------

# Plot: D1 (anxiety) category vs. weekdays - rel
D1_vs_weekday_category_rel <- ggplot(data = table_D1_weekday_per_D1, 
                                     mapping = aes(x = day_of_week, y = perc, fill = D1)) +
  geom_bar(position = "dodge", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D1 (anxiety) per weekday", 
       x = "Day of the week",
       y = "Relative frequency") + 
  scale_fill_brewer(palette = "Blues", name = "D1 (anxiety)") +
  geom_text(aes(label=round(perc, 2)),
            position=position_dodge(width=0.9),
            vjust=-0.2, size=3.75) +
  theme(text = element_text(size = 15))
# Plot: D2 (depression) category vs. weekdays - rel
D2_vs_weekday_category_rel <- ggplot(data = table_D2_weekday_per_D2, 
                                     mapping = aes(x = day_of_week, y = perc, fill = D2)) +
  geom_bar( position = "dodge", stat = "identity") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1)) +
  labs(title = "Relative frequency of D2 (depression) per weekday", 
       x = "Day of the week",
       y = "Relative frequency") + 
  scale_fill_brewer(palette = "Blues", name = "D2 (depression)") +
  geom_text(aes(label=round(perc, 2)),
            position=position_dodge(width=0.9),
            vjust=-0.2, size=3.75) +
  theme(text = element_text(size = 15)) 

ggarrange(D1_vs_weekday_category_rel, D2_vs_weekday_category_rel, ncol = 1, nrow = 2,
          labels = c("A", "B", "C", "D"), common.legend = TRUE, legend = "bottom")
ggsave("Plots/paper/arranged_D1_D2_vs_weekday_category_rel.png", width = 12, height = 9)

## -----------

# Plot: D1 (anxiety) vs. weekdays - abs
D1_vs_weekday_abs <- ggplot(data = table_D1_weekday, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Observations D1 (anxiety) per weekdays", 
       x = "Day of the week",
       y = "Number of observations") +
  geom_text(aes(label = n), vjust = -0.25) +
  theme(text = element_text(size = 15))
# Plot: D2 (depression) vs. weekdays - abs
D2_vs_weekday_abs <- ggplot(data = table_D2_weekday, mapping = aes(x = day_of_week, y = n)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Observations D2 (depression) per weekdays", 
       x = "Day of the week",
       y = "Number of observations") +
  geom_text(aes(label = n), vjust = -0.25) +
  theme(text = element_text(size = 15))

ggarrange(D1_vs_weekday_abs, D2_vs_weekday_abs, ncol = 1, nrow = 2,
          labels = c("A", "B", "C", "D"))
ggsave("Plots/paper/arranged_D1_D2_vs_weekday_abs.png", width = 12, height = 9)

## -----------

# Plot: Observations region_agg (federal state)
ggplot(data = CTIS_microdata, mapping = aes(x = region_agg)) +
  geom_bar() +
  coord_flip() +
  labs(title = "Number of observations per federal state",
       x = "Federal state",
       y = "Number of Observations") +
  geom_text(stat="count", aes(label=..count..),
            hjust=0, size=5) +
  theme(text = element_text(size = 15))
ggsave("Plots/paper/Obs_region_agg_barplot.png", width = 12, height = 9)

## -----------

# Save the crosstable of D1 and D2 as a latex code
cross_table_D1_D2 <- table(CTIS_microdata$D1, CTIS_microdata$D2)

knitr::kable(x = cross_table_D1_D2, format = "latex") %>%
  kableExtra::add_header_above(c("D1 (anxiety)" = 1, "D2 (depression)" = 5))

## -----------

bl_massnahmen_index_tag$alpha_values <- ifelse(bl_massnahmen_index_tag$included_in_study, 1, 0.8)
# Plot: German restriction index over time by federal state 
ggplot(data = bl_massnahmen_index_tag, mapping = aes(x = datum, y = bl_mn_idx_t, color = bundesland)) +
  geom_line(aes(alpha = alpha_values)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(x = "Date",
       y = "General containment measures index",
       color = "Federal state") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))
ggsave(filename = "Plots/paper/gen_measures_date.png", width = 12, height = 6)

bl_massnahmen_index_tag %>% 
  filter(included_in_study) %>%
  arrange(desc(bl_mn_idx_t))

bl_massnahmen_index_tag %>% 
  filter(included_in_study) %>%
  arrange(bl_mn_idx_t)

bl_massnahmen_index_tag %>% 
  filter(included_in_study) %>%
  ungroup() %>% 
  group_by(datum) %>% 
  summarise(min_bl_mn_idx_t = min(bl_mn_idx_t), max_bl_mn_idx_t = max(bl_mn_idx_t),
            diff_bl_mn_idx_t = max_bl_mn_idx_t - min_bl_mn_idx_t) %>%
  arrange(diff_bl_mn_idx_t)

bl_massnahmen_index_tag %>% 
  filter(included_in_study) %>%
  ungroup() %>% 
  group_by(datum) %>% 
  summarise(min_bl_mn_idx_t = min(bl_mn_idx_t), max_bl_mn_idx_t = max(bl_mn_idx_t),
            diff_bl_mn_idx_t = max_bl_mn_idx_t - min_bl_mn_idx_t) %>%
  arrange(desc(diff_bl_mn_idx_t))

## -----------

# Plot: German restriction index over time for Bavaria 
ggplot(data = filter(bl_massnahmen_index_tag, bundesland == "Bayern"), 
       mapping = aes(x = datum, y = bl_mn_idx_t)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  geom_line(aes(alpha = alpha_values))  +
  labs(x = "Date",
       y = "General containment measures index") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))
ggsave(filename = "Plots/paper/gen_measures_date_bavaria.png", width = 12, height = 6)

## -----------

bl_massnahmen_index_tag$alpha_values <- ifelse(bl_massnahmen_index_tag$included_in_study, 1, 0.8)
# Plot: German restriction index (Daycare centers) over time by federal state 
measures_daycare_date <- ggplot(data = bl_massnahmen_index_tag, 
                                mapping = aes(x = datum, y = bl_mn_idx_t_m03, color = bundesland)) +
  geom_line(aes(alpha = alpha_values)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German daycare centers measures index\nover time per federal states",
       x = "Date",
       y = "Daycare centers measures\nindex",
       color = "Federal state") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))

# Plot: German restriction index (Secondary schools) over time by federal state 
measures_sec_schools_date <- ggplot(data = bl_massnahmen_index_tag, 
                                    mapping = aes(x = datum, y = bl_mn_idx_t_m02a, color = bundesland)) +
  geom_line(aes(alpha = alpha_values)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "German secondary schools measures index\nover time per federal states",
       x = "Date",
       y = "Secondary schools measures\nindex",
       color = "Federal state") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))

# Plot: German restriction index (Elementary schools) over time by federal state 
measures_elem_schools_date <- ggplot(data = bl_massnahmen_index_tag, 
                                     mapping = aes(x = datum, y = bl_mn_idx_t_m02b, color = bundesland)) +
  geom_line(aes(alpha = alpha_values)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "Elementary schools measures index\nover time per federal states",
       x = "Date",
       y = "German elementary schools measures\nindex",
       color = "Federal state") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))

# Plot: German restriction index (Mask obligation) over time by federal state 
measures_maks_date <- ggplot(data = bl_massnahmen_index_tag, 
                             mapping = aes(x = datum, y = bl_mn_idx_t_m16, color = bundesland)) +
  geom_line(aes(alpha = alpha_values)) +
  geom_vline(xintercept = c(as.Date("2022-06-25"), as.Date("2021-05-20")), linetype="dashed") +
  labs(title = "Mask obligation index\nover time per federal states",
       x = "Date",
       y = "German mask obligation\nindex",
       color = "Federal state") +
    scale_alpha_continuous(guide="none") +
  theme(text = element_text(size = 15))

ggarrange(measures_daycare_date, measures_sec_schools_date, 
          measures_elem_schools_date, measures_maks_date,
          ncol = 2, nrow = 2,
          labels = c("A", "B", "C", "D"), common.legend = TRUE, legend = "bottom",
          font.label=list(color="black",size=15))
ggsave("Plots/paper/arranged_other_indicies.png", width = 12, height = 15)

unique(bl_massnahmen_index_tag$bl_mn_idx_t_m03)

## -----------

# # Plot: D1 vs German restriction index
# D1_restr_boxplot <- ggplot(data = micro_restr %>% select(D1, bl_mn_idx_t) %>% drop_na(), 
#        mapping = aes(x = D1, y = bl_mn_idx_t)) +
#   geom_boxplot() +
#   stat_summary(
#     fun.data = stat_box_data_80, 
#     geom = "text", 
#     hjust = 0.5,
#     vjust = 0.9
#   ) +
#   labs(title = "Relationship between D1 (anxiety) and the german general containment measures",
#        x = "D1 (anxiety)",
#        y = "General containment\nmeasures index") +
#   theme(text = element_text(size = 15))
# 
# # Plot: D2 vs German restriction index
# D2_restr_boxplot <- ggplot(data = micro_restr %>% select(D2, bl_mn_idx_t) %>% drop_na(), 
#        mapping = aes(x = D2, y = bl_mn_idx_t)) +
#   geom_boxplot() +
#   stat_summary(
#     fun.data = stat_box_data_80, 
#     geom = "text", 
#     hjust = 0.5,
#     vjust = 0.9
#   ) +
#   labs(title = "Relationship between D2 (depression) and the german general containment measures",
#        x = "D2 (depressed)",
#        y = "General containment\nmeasures index") +
#   theme(text = element_text(size = 15))
# 
# ggarrange(D1_restr_boxplot, D2_restr_boxplot, ncol = 1, nrow = 2,
#           labels = c("A", "B", "C", "D"))
# ggsave("Plots/paper/arranged_gen_measures_D1_D2.png", width = 12, height = 9)
# 
# micro_restr %>%
#   group_by(D1) %>%
#   summarise(n(),
#             mean(bl_mn_idx_t),
#             median(bl_mn_idx_t),
#             quantile(bl_mn_idx_t, .25),
#             quantile(bl_mn_idx_t, .75))
# 
# micro_restr %>%
#   group_by(D2) %>%
#   summarise(n(),
#             mean(bl_mn_idx_t),
#             median(bl_mn_idx_t),
#             quantile(bl_mn_idx_t, .25),
#             quantile(bl_mn_idx_t, .75))
# 
# ## -----------
# 
# # Plot: D1 vs German restriction index vs E4
# D1_restr_E4_boxplot <- ggplot(data = micro_restr %>% select(D1, E4, bl_mn_idx_t) %>% drop_na(), 
#        mapping = aes(x = D1, y = bl_mn_idx_t)) +
#   stat_summary(
#     fun.data = stat_box_data, 
#     geom = "text", 
#     hjust = 0.5,
#     vjust = 0.9
#   ) +
#     geom_boxplot(aes(color = E4)) +
#     labs(title = "Relationship between D1 (anxiety) and the german general containment measures per age group",
#          x = "D1 (anxious)",
#          y = "General containment measures index") + 
#     scale_color_brewer(palette = "Blues", name = "E4 (age group)") +
#   theme(text = element_text(size = 15)) +
#   theme_gray()
# 
# # Plot: D2 vs German restriction index vs E4
# D2_restr_E4_boxplot <- ggplot(data = micro_restr %>% select(D2, E4, bl_mn_idx_t) %>% drop_na(), 
#        mapping = aes(x = D2, y = bl_mn_idx_t)) +
#   stat_summary(
#     fun.data = stat_box_data, 
#     geom = "text", 
#     hjust = 0.5,
#     vjust = 0.9
#   ) +
#     geom_boxplot(aes(color = E4)) +
#     labs(title = "Relationship between D2 (depression) and the german general containment measures per age group",
#          x = "D2 (depressed)",
#          y = "General containment measures index") + 
#     scale_color_brewer(palette = "Blues", name = "E4 (age group)") +
#   theme(text = element_text(size = 15)) +
#   theme_gray()
# 
# ggarrange(D1_restr_E4_boxplot, D2_restr_E4_boxplot, ncol = 1, nrow = 2,
#           labels = c("A", "B", "C", "D"), common.legend = TRUE, legend = "bottom",
#           font.label=list(color="black",size=15))
# ggsave("Plots/paper/arranged_gen_measures_D1_D2_E4.png", width = 12, height = 12)
# 
# micro_restr %>%
#   group_by(D1, E4) %>%
#   summarise(n(),
#             mean(bl_mn_idx_t),
#             median(bl_mn_idx_t),
#             quantile(bl_mn_idx_t, .25),
#             quantile(bl_mn_idx_t, .75))
# 
# micro_restr %>%
#   group_by(D2, E4) %>%
#   summarise(n(),
#             mean(bl_mn_idx_t),
#             median(bl_mn_idx_t),
#             quantile(bl_mn_idx_t, .25),
#             quantile(bl_mn_idx_t, .75))

## -----------

# Plot: D1 vs German restriction index
D1_gen_restr_lineplot <- micro_restr %>% select(D1, bl_mn_idx_t) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(bl_mn_idx_t) %>%
    filter(all(n >= 10)) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
  labs(title = "Relative frequency of D1 (anxiety) categories across general containment measures index",
       x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")

# Plot: D2 vs German restriction index
D2_gen_restr_lineplot <- micro_restr %>% select(D2, bl_mn_idx_t) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(bl_mn_idx_t) %>%
    filter(all(n >= 10)) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
  labs(title = "Relative frequency of D2 (depression) categories across general containment measures index",
       x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")

ggarrange(D1_gen_restr_lineplot, D2_gen_restr_lineplot, ncol = 1, nrow = 2,
          labels = c("A", "B", "C", "D"))
ggsave("Plots/paper/arranged_D1_D2_gen_measures.png", width = 12, height = 12)

## -----------

# Plot: D1 vs German restriction index vs E4
micro_restr %>% select(D1, bl_mn_idx_t, E4) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E4, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E4, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D1)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E4) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D1_gen_measures_E4.png", width = 12, height = 12)

## -----------

# Plot: D2 vs German restriction index vs E4
micro_restr %>% select(D2, bl_mn_idx_t, E4) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E4, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E4, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E4) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D2_gen_measures_E4.png", width = 12, height = 12)

micro_restr %>% select(D2, bl_mn_idx_t, E4) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E4, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E4, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
  filter(E4 == "18-24", D2 == "Some of the time") %>%
  arrange(desc(perc))

## -----------

# Plot: D1 vs German restriction index vs E8
micro_restr %>% select(D1, bl_mn_idx_t, E8) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E8, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E8, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D1)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E8) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D1_gen_measures_E8.png", width = 12, height = 12)

## -----------

# Plot: D2 vs German restriction index vs E8
micro_restr %>% select(D2, bl_mn_idx_t, E8) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E8, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E8, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E8) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D2_gen_measures_E8.png", width = 12, height = 12)


## -----------

# Plot: D1 vs German restriction index vs E3
micro_restr %>% select(D1, bl_mn_idx_t, E3) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E3, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E3, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D1)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E3) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D1_gen_measures_E3.png", width = 12, height = 12)

## -----------

# Plot: D2 vs German restriction index vs E3
micro_restr %>% select(D2, bl_mn_idx_t, E3) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E3, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E3, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E3) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D2_gen_measures_E3.png", width = 12, height = 12)


## -----------

# Plot: D1 vs German restriction index vs E2
micro_restr %>% select(D1, bl_mn_idx_t, E2) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E2, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E2, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D1)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E2) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D1_gen_measures_E2.png", width = 12, height = 12)

## -----------

# Plot: D2 vs German restriction index vs E2
micro_restr %>% select(D2, bl_mn_idx_t, E2) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, E2, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(E2, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~E2) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D2_gen_measures_E2.png", width = 12, height = 12)

## -----------

# Plot: D1 vs German restriction index vs D7a
micro_restr %>% select(D1, bl_mn_idx_t, D7a) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, D7a, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(D7a, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D1)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~D7a) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D1 (anxiety)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D1_gen_measures_D7a.png", width = 12, height = 12)

## -----------

# Plot: D2 vs German restriction index vs D7a
micro_restr %>% select(D2, bl_mn_idx_t, D7a) %>% ungroup() %>%
    mutate(bl_mn_idx_t = round(bl_mn_idx_t)) %>%
    group_by(bl_mn_idx_t, D7a, D2) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ungroup() %>%
    group_by(D7a, bl_mn_idx_t) %>%
    filter(all(n >= 3),
           length(unique(D2)) == 5) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D2)) +
    geom_line() +
  geom_point(size = 0.75) +
    facet_wrap(~D7a) +
  labs(x = "General containment measures index",
       y = "Relative frequency",
       color = "D2 (depression)") +
  theme(text = element_text(size = 15),
        legend.position = "bottom")
ggsave("Plots/paper/lineplot_D2_gen_measures_D7a.png", width = 12, height = 12)

micro_restr %>% select(D1, bl_mn_idx_t) %>% ungroup() %>%
    group_by(bl_mn_idx_t, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
    geom_smooth()

micro_restr %>% select(D1, bl_mn_idx_t, E4) %>% ungroup() %>%
    group_by(bl_mn_idx_t, E4, D1) %>%
    summarise(n = n()) %>%
    mutate(perc = n/sum(n)) %>%
    ggplot(aes(x = bl_mn_idx_t, y = perc, color = D1)) +
    geom_line() +
    geom_smooth() +
    facet_wrap(~E4)
```

