---
title: "Data Preparation"
author: "Christian Hobelsberger"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(httr)
library(jsonlite)
library(data.table)
devtools::install_github("CaroHaensch/CTIS")
library(CTIS)
```

## Import Corona data from Germany

For this I use the CKAN Data API: <https://www.corona-daten-deutschland.de/api/1/util/snippet/api_info.html?resource_id=09536dc7-d81b-4c79-badc-b0c48a2f6385>
Query code from: <https://www.r-bloggers.com/2019/06/getting-open-data-into-r-from-ckan/>
```{r Import Corona data from Germany}
# Import data on curfew in Germany

## Measures index federal states per day ----------------------------------------------------
url_fed_states <- "https://www.corona-daten-deutschland.de/api/3/action/datastore_search_sql?sql=SELECT%20*%20from%20%22dff8926f-3006-4260-bc71-06b86d521811%22%20"
page_fed_states <- GET(url_fed_states) # API request
status_code(page_fed_states) # # Check that the call is successful
# [1] 200
# This means it was successful
# Status codes:
# 1XX - Informational
# 2XX - Success!
# 3XX - Client Error (something’s not right on your end)
# 4XX - Server Error (something’s not right on their end)
# Download the JSON data and convert to an R list
bl_massnahmen_index_tag_list <- fromJSON(url_fed_states)
# Extract the actual data from the list
bl_massnahmen_index_tag <- bl_massnahmen_index_tag_list$result$records
glimpse(bl_massnahmen_index_tag, width = 50)

col_order_fed_states <- c("ags2", "bundesland", "datum", "bl_mn_idx_t", "bl_mn_idx_t_m02a", "bl_mn_idx_t_m02b", 
                          "bl_mn_idx_t_m03", "bl_mn_idx_t_m16")
bl_massnahmen_index_tag <- bl_massnahmen_index_tag[, col_order_fed_states]

bl_massnahmen_index_tag <- transform(bl_massnahmen_index_tag,
                                     ags2 = as.factor(ags2), 
                                     bundesland = as.factor(bundesland),
                                     datum = as.Date(datum),
                                     bl_mn_idx_t = as.numeric(bl_mn_idx_t),
                                     bl_mn_idx_t_m02a = as.numeric(bl_mn_idx_t_m02a),
                                     bl_mn_idx_t_m02b = as.numeric(bl_mn_idx_t_m02b),
                                     bl_mn_idx_t_m03 = as.numeric(bl_mn_idx_t_m03),
                                     bl_mn_idx_t_m16 = as.numeric(bl_mn_idx_t_m16))

# Adjust regional-levels to match CTIS data
levels(bl_massnahmen_index_tag$bundesland)[5] <- "Bayern"

saveRDS(object = bl_massnahmen_index_tag, file = "data/protected_data/bl_massnahmen_index_tag.RDS")


## Measures subcategories counties ----------------------------------------------------------


url_counties <- "https://www.corona-daten-deutschland.de/api/3/action/datastore_search_sql?sql=SELECT%20*%20from%20%2209536dc7-d81b-4c79-badc-b0c48a2f6385%22"
page_counties <- GET(url_counties) # API request
status_code(page_counties) # # Check that the call is successful
# [1] 200
# This means it was successful
# Status codes:
# 1XX - Informational
# 2XX - Success!
# 3XX - Client Error (something’s not right on your end)
# 4XX - Server Error (something’s not right on their end)
# Download the JSON data and convert to an R list
kr_massn_unterkat_m18_list <- fromJSON(url_counties)
# Extract the actual data from the list
kr_massn_unterkat_m18 <- kr_massn_unterkat_m18_list$result$records
glimpse(kr_massn_unterkat_m18, width = 50)

col_order <- c("ags5", "kreis", "datum", "code_m18_010", "code_m18_010_1", "code_m18_010_2", "code_m18_010_3", 
               "code_m18_010_4", "code_m18_010_5", "code_m18_020", "code_m18_020_1", "code_m18_020_2", "code_m18_020_3",
               "code_m18_020_4", "code_m18_020_5", "code_m18_030", "code_m18_030_1", "code_m18_030_2", "code_m18_030_3",
               "code_m18_030_4", "code_m18_030_5", "code_m18_040", "code_m18_040_1", "code_m18_040_2", "code_m18_040_3",
               "code_m18_040_4", "code_m18_040_5")
kr_massn_unterkat_m18 <- kr_massn_unterkat_m18[, col_order]



saveRDS(object = kr_massn_unterkat_m18, file = "data/protected_data/kr_massn_unterkat_m18.RDS")
```

## Skript to download microdata
We are using the R Package CTIS to get access to the API Interface, more information on <https://github.com/CaroHaensch/CTIS>.

```{r Skript to download microdata, echo=FALSE}
setwd("data/protected_data/microdata")
date_vec <- seq(as.Date("2020-04-23"), as.Date("2022-06-25"), by = "day") # Second date is end date
username <- readline(prompt = "Enter username for CTIS login: ")
password <- readline(prompt = "Enter password for CTIS login: ")
# Download microdata files
for (date_index in seq_len(length(date_vec))) {
  CTIS::CTIS_microdata(username = username, password = password, date = as.character(date_vec[date_index]), type = "full")
}

# Combine microdata
colum_name_vec = c("survey_region", "survey_version", "weight", "Finished", "RecordedDate", "country_agg",
                   "country_region_numeric", "region_agg", "intro1", "intro2", "B0", "G1", "D1", "D2",
                   "D4", "D5", "J1", "E3", "E4", "E8", "E2", "E5", "E7a", "D7a", "D10")
# Create list of files
csv_files <- list.files(pattern = "\\.csv$")

# Create dataframe with all dates and country "Germany" (see country_region_numeric %in% 1143:1159)
CTIS_microdata <- data.frame()
for (file in csv_files) {
  CTIS_microdata <- bind_rows(CTIS_microdata,
            readr::read_csv(file = file,
                            col_names = TRUE,
                            col_select = any_of(colum_name_vec),
                            col_types = c(.default = "d", survey_region = "f", country_agg = "f", 
                                          region_agg = "f", RecordedDate = "f")) %>% 
              filter(country_region_numeric %in% 1143:1159))
}
setwd("..")
write_csv(x = CTIS_microdata, file = "CTIS_microdata_raw.csv")
setwd("~/git/CTIS-Mental-Health-Restrictions")
```

# Cleaning up microdata
```{r}
# Load microdata raw
CTIS_microdata_raw <- read_csv(file = "data/protected_data/CTIS_microdata_raw.csv", col_names = TRUE,
                               col_types = c(.default = "f", weight = "d", RecordedDate = "T", 
                                             J1 = "d", E5 = "d", E7a = "d"),
                               na = c("NA", "-99", "-88", "-77"))

# Remove wrong countries & regions
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(country_agg == "Germany")
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(survey_region == "EU")
CTIS_microdata_raw$country_agg <- droplevels(CTIS_microdata_raw$country_agg) # Drop other levels
CTIS_microdata_raw$region_agg <- droplevels(CTIS_microdata_raw$region_agg) # Drop other levels
CTIS_microdata_raw$survey_region <- droplevels(CTIS_microdata_raw$survey_region) # Drop other levels

# TODO: Possibly clean survey_region levels -> ROW

# Adjust levels for data
levels(CTIS_microdata_raw$D1) <- list(
  "None of the time" = "5",
  "A little of the time" = "4",
  "Some of the time" = "3",
  "Most of the time" = "2",
  "All the time" = "1"
)

levels(CTIS_microdata_raw$D2) <- list(
  "None of the time" = "5",
  "A little of the time" = "4",
  "Some of the time" = "3",
  "Most of the time" = "2",
  "All the time" = "1"
)

levels(CTIS_microdata_raw$D4) <- list(
  "Not worried at all" = "4",
  "Not too worried" = "3",
  "Somewhat worried" = "2",
  "Very worried" = "1"
)

levels(CTIS_microdata_raw$E3) <- list(
  "Male" = "1",
  "Female" = "2",
  "Other" = "3",
  "Prefer not to answer" = "4"
)

levels(CTIS_microdata_raw$E4) <- list(
  "18-24" = "1",
  "25-34" = "2",
  "35-44" = "3",
  "45-54" = "4",
  "55-64" = "5",
  "65-74" = "6",
  "75+" = "7"
)

levels(CTIS_microdata_raw$E2) <- list(
  "City" = "1",
  "Town" = "2",
  "Village or rural area" = "3"
)

levels(CTIS_microdata_raw$D5) <- list(
  "Not worried at all" = "4",
  "Not too worried" = "3",
  "Somewhat worried" = "2",
  "Very worried" = "1"
)


levels(CTIS_microdata_raw$D10) <- list(
  "Agriculture" = "1",
  "Buying and selling" = "2",
  "Construction" = "3",
  "Education" = "4",
  "Electricity/water/gas/waste" = "5",
  "Financial/insurance/real estate services" = "6",
  "Health" = "7",
  "Manufacturing" = "8",
  "Mining" = "9",
  "Personal services" = "10",
  "Professional/scientific/technical activities" = "11",
  "Public administration" = "12",
  "Tourism" = "13",
  "Transportation" = "14",
  "Other" = "15"
)

levels(CTIS_microdata_raw$B0) <- list(
  "Yes" = "1",
  "No" = "2"
)

levels(CTIS_microdata_raw$G1) <- list(
  "Not at all" = "4",
  "A little" = "3",
  "A moderate amount" = "2",
  "A great deal" = "1"
)

levels(CTIS_microdata_raw$E8) <- list(
  "No formal schooling" = "1",
  "Less than primary school" = "2",
  "Primary school completed" = "3",
  "Secondary school complete" = "4",
  "High school (or equivalent) completed" = "5",
  "College/ pre-university/ University completed" = "6",
  "University post-graduate degree completed" = "7"
)

levels(CTIS_microdata_raw$D7a) <- list(
  "Yes" = "1",
  "No" = "2"
)

# Filter dates until June 12, 2022 because of survey end
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(RecordedDate < as.Date("2022-06-26"))

# Recoding from 0 to 1 of the variable E5 („How many people slept in the place where you stayed last night 
# (including yourself)”)
CTIS_microdata_raw["E5"][CTIS_microdata_raw["E5"] == 0] <- 1

# Filter for sensible E5, J1, E7a
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(is.na(E5) | (E5 == as.integer(E5) & E5 <= 50))
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(is.na(J1) | (J1 == as.integer(J1) & J1 <= 12))
CTIS_microdata_raw <- CTIS_microdata_raw %>% filter(is.na(E7a) | (E7a == as.integer(E7a) & E7a <= 50))
# Create Date column
CTIS_microdata_raw$Date <- as.Date(CTIS_microdata_raw$RecordedDate)

# set factor levels for region_agg
CTIS_microdata_raw$region_agg <- 
  factor(CTIS_microdata_raw$region_agg,levels(CTIS_microdata_raw$region_agg)[order(as.vector(levels(CTIS_microdata_raw$region_agg)))])

saveRDS(object = CTIS_microdata_raw, file = "data/protected_data/CTIS_microdata.RDS")
```


```{r Import region mapping file, echo=FALSE}
# Import region mapping file
CTIS_survey_country_region_map_table <- read_csv(file = "data/CTIS_survey_country_region_map_table.csv")

# Filter table for Germany
CTIS_survey_country_region_map_table <- CTIS_survey_country_region_map_table %>%
  filter(country_agg == "Germany")

# Regions in Germany
regions <- as.vector(na.omit(unique(CTIS_survey_country_region_map_table$region_agg)))
```

```{r Skript to import macrodata, echo=FALSE}
indicator_list = list("anxious_7d", "depressed_7d", "worried_become_ill", "finance", "food_security")
macrodata_list <- list()
for (region_counter in regions) {
  data_tmp_reg <- lapply(X = c(indicator_list, regions), 
                         FUN = function(x){
                           CTIS_open_data_region(indicator = x, type = "daily", country = "Germany", 
                                                 region = region_counter, daterange = "")
                           })
  macrodata_list <- append(macrodata_list, data_tmp_reg)
}
# data <- lapply(X = c(indicator_list, regions), 
#                FUN = function(x){
#                  CTIS_open_data_region(indicator = x, type = "daily", country = "Germany", region = "Bayern", daterange = "")
#                  })
data <- as.data.frame(do.call(rbind, macrodata_list))
data_trimmed <- data[,c(1:9)]
# avg. data.sample_size because of differences in the same day

data_trimmed <- data_trimmed %>% 
  group_by(data.region, data.survey_date) %>% 
  mutate(average_sample_size = mean(data.sample_size)) %>% 
  ungroup()

# replace the original sample_size column with the averaged sample size
data_trimmed$data.sample_size <- data_trimmed$average_sample_size

# remove the average_sample_size column
data_trimmed$average_sample_size <- NULL

data_aggregated <- dcast(data = as.data.table(data_trimmed), 
                         formula = data.country+data.region+data.iso_code+data.gid_0+data.gid_1+data.survey_date+data.sample_size~data.indicator, 
                         value.var = "data.pct")
data_aggregated$data.country <- as.factor(data_aggregated$data.country)
data_aggregated$data.region <- as.factor(data_aggregated$data.region)
data_aggregated$data.iso_code <- as.factor(data_aggregated$data.iso_code)
data_aggregated$data.gid_0 <- as.factor(data_aggregated$data.gid_0)
data_aggregated$data.gid_1 <- as.factor(data_aggregated$data.gid_1)
data_aggregated$data.survey_date <- as.Date(x = data_aggregated$data.survey_date, "%Y%m%d")

saveRDS(object = data_aggregated, file = "data/protected_data/macrodata.RDS")
```

## Merge macrodata and german restriction data

```{r merge macro and restriction data}
bl_massnahmen_index_tag <- readRDS(file = "data/protected_data/bl_massnahmen_index_tag.RDS")
macrodata <- readRDS(file = "data/protected_data/macrodata.RDS")

macro_restr <- merge(x=macrodata,y=bl_massnahmen_index_tag, by.x=c("data.region","data.survey_date"), 
                     by.y=c("bundesland","datum"), all.x = TRUE)
saveRDS(object = macro_restr, file = "data/protected_data/macro_restr.RDS")

```

## Merge microdata and german restriction data

```{r merge macro and restriction data}
bl_massnahmen_index_tag <- readRDS(file = "data/protected_data/bl_massnahmen_index_tag.RDS")
CTIS_microdata <- readRDS(file = "data/protected_data/CTIS_microdata.RDS")

micro_restr <- merge(x=CTIS_microdata,y=bl_massnahmen_index_tag, by.x=c("region_agg","Date"), 
                     by.y=c("bundesland","datum"), all.x = TRUE)
saveRDS(object = micro_restr, file = "data/protected_data/micro_restr.RDS")

```
