---
output:
  word_document: default
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
# install.packages("pander")
# install.packages("desctable")
# install.packages("memisc")
# library(tidyverse)
# 
# 
# # Read microdata with restriction data
# micro_restr <- readRDS(file = "data/protected_data/micro_restr.RDS")
# 
# # D1 = nervous, D2 = depressed, E4 = Age, E3 = Gender, E8 = Education, E2 = Where do you live,
# # E5 = People slept in the same place, E7a = Rooms used for sleeping, D7a = Paid work,
# # bl_mn_idx_t = Measures index federal states per day, bl_mn_idx_t_m02a = Index (Secondary schools),
# # bl_mn_idx_t_m02b = Index (Elementary Schools), bl_mn_idx_t_m03 = Index = Index (Daycare centers),
# # bl_mn_idx_t_m16 = Index (Mask obligation)
# 
# micro_restr[, c("D1", "D2", "E4", "E3", "E8", "E2", "E5", "E7a", "D7a", "bl_mn_idx_t", "bl_mn_idx_t_m02a",
#                "bl_mn_idx_t_m02b", "bl_mn_idx_t_m03", "bl_mn_idx_t_m16")] %>%
#     `colnames<-` (c("During the past 7 days, how often did you feel so nervous that nothing could calm you down? (D1)",
#                     "During the past 7 days, how often did you feel so depressed that nothing could cheer you up? (D2)",
#                     "What is your age?",
#                     "What is your gender?",
#                     "What is the highest level of education that you have completed?",
#                     "Which of these best describes the area where you are currently staying?",
#                     "How many people slept in the place where you stayed last night (including yourself)?",
#                     "How many rooms are used for sleeping in the place where you are staying?",
#                     "In the past 4 weeks, did you do any work for pay?",
#                     "Index (0-100%) for the severity of containment measures imposed per day: General",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Secondary schools",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Elementary Schools",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Daycare centers",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Mask obligation"
#                     )) |> desctable::desc_table(
#                       "N"      = length,
#                       "%"      = memisc::percent,
#                       "Med"    = median,
#                       "Mean"   = mean,
#                       "IQR"    = IQR
#                     ) |> pander::pander()
```

--------------------------------------------------------------------------
           Variables                N        %       Med    Mean     IQR  
-------------------------------- -------- -------- ------- ------- -------
 **During the past 7 days, how    522070    --       --      --       --   
 often did you feel so nervous                                            
  that nothing could calm you                                             
          down? (D1)**                                                    

*None of the time*                362875   69.51     --      --       --  

*A little of the time*            82481    15.8      --      --       --  

*Some of the time*                58261    11.16     --      --       --  

 *Most of the time*               12668    2.426     --      --       --  

*All the time*                     5785    1.108     --      --       --  

 **During the past 7 days, how    522070    --       --      --       --   
     often did you feel so                                                
  depressed that nothing could                                            
      cheer you up? (D2)**                                                

*None of the time*                306068   58.63     --      --       --  

*A little of the time*            94338    18.07     --      --       --  

*Some of the time*                84521    16.19     --      --       --  

*Most of the time*                25523    4.889     --      --       --  

*All the time*                    11620    2.226     --      --       --  

     **What is your age?**        522070    --       --      --       --   

 *18-24*                          20251    3.879     --      --       --  

 *25-34*                          90475    17.33     --      --       --  

 *35-44*                          124396   23.83     --      --       --  

 *45-54*                          119116   22.82     --      --       --  

 *55-64*                          105750   20.26     --      --       --  

 *65-74*                          50577    9.688     --      --       --  

  *75+*                           11505    2.204     --      --       --  

    **What is your gender?**      522070    --       --      --       --   

   *Male*                         226811   43.44     --      --       --  

   *Female*                       290789   55.7      --      --       --  

   *Other*                         1501    0.2875    --      --       --  

   *Prefer not to answer*          2969    0.5687    --      --       --  

 **What is the highest level of   522070    --       --      --       --   
    education that you have                                               
          completed?**                                                    

 *No formal schooling*             1784    0.3417    --      --       --  

*Less than primary school*         3857    0.7388    --      --       --  

*Primary school completed*        22476    4.305     --      --       --  

*Secondary school complete*       168656   32.31     --      --       --  

*High school (or                  166316   31.86     --      --       --  
equivalent) completed*

*College/                         107209   20.54     --      --       --  
   pre-university/ University                                             
           completed*                                                     

*University                       51772    9.917     --      --       --  
      post-graduate degree                                                
           completed*                                                     

     **Which of these best        522070   --       --      --       --   
  describes the area where you                                            
    are currently staying?**                                              

*City*                            201459   38.59     --      --       --  
                                                      

*Town*                            147563   28.26     --      --       --  

*Village or rural area*           173048   33.15     --      --       --  

**How many people slept in the    522070     --       2     2.555     2
  place where you stayed last                                             
  night (including yourself)?**                                             

**How many rooms are used for     522070     --       2     1.975     2 
  sleeping in the place where                                             
        you are staying?**                                                  

 **In the past 4 weeks, did you   522070    --       --      --       --      
     do any work for pay?**                                               

*Yes*                             376772   72.17     --      --       --  

*No*                              145298   27.83     --      --       --  

  **Index (0-100%) for the        522070     --     40.32   35.62   15.82 
    severity of containment                                               
   measures imposed per day:                                              
            General**                                                       

**Index (0-100) for the severity  522070     --     40.6    39.71   39.6  
    of containment measures                                               
 prescribed per day: Secondary                                            
            schools**                                                       

**Index (0-100) for the severity  522070     --     40.6    36.6    19.8  
    of containment measures                                               
 prescribed per day: Elementary                                           
            Schools**                                                       

**Index (0-100) for the severity  522070     --     20.8    29.45   19.8    
    of containment measures                                               
  prescribed per day: Daycare                                             
            centers**                                                       

**Index (0-100) for the severity  522070     --      56     51.16    22   
    of containment measures                                               
    prescribed per day: Mask                                              
           obligation**                                                     
--------------------------------------------------------------------------