---
output:
  pdf_document: default
  html_document: default
---
```{r setup, include=FALSE}
#  -------------------------FOR PDF-----------------------------------
# install.packages("pander")
# install.packages("desctable")
# install.packages("memisc")
# 
# 
# # Read microdata with restriction data
# micro_restr <- readRDS(file = "data/protected_data/micro_restr.RDS")
# 
# # D1 = nervous, D2 = depressed, E4 = Age, E3 = Gender, E8 = Education, E2 = Where do you live,
# # E5 = People slept in the same place, E7a = Rooms used for sleeping, D7a = Paid work,
# # bl_mn_idx_t = Measures index federal states per day, bl_mn_idx_t_m02a = Index (Secondary schools),
# # bl_mn_idx_t_m02b = Index (Elementary Schools), bl_mn_idx_t_m03 = Index = Index (Daycare centers),
# # bl_mn_idx_t_m16 = Index (Mask obligation)
# 
# micro_restr[, c("D1", "D2", "E4", "E3", "E8", "E2", "E5", "E7a", "D7a", "bl_mn_idx_t", "bl_mn_idx_t_m02a",
#                "bl_mn_idx_t_m02b", "bl_mn_idx_t_m03", "bl_mn_idx_t_m16")] %>%
#     `colnames<-` (c("During the past 7 days, how often did you feel so nervous that nothing could calm you down? (D1)", 
#                     "During the past 7 days, how often did you feel so depressed that nothing could cheer you up? (D2)",
#                     "What is your age?", 
#                     "What is your gender?", 
#                     "What is the highest level of education that you have completed?", 
#                     "Which of these best describes the area where you are currently staying?", 
#                     "How many people slept in the place where you stayed last night (including yourself)?",
#                     "How many rooms are used for sleeping in the place where you are staying?",
#                     "In the past 4 weeks, did you do any work for pay?",
#                     "Index (0-100%) for the severity of containment measures imposed per day: General",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Secondary schools",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Elementary Schools",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Daycare centers",
#                     "Index (0-100) for the severity of containment measures prescribed per day: Mask obligation"
#                     )) |> desctable::desc_table(
#                       "N"      = length,
#                       "%"      = memisc::percent,
#                       "Med"    = median,
#                       "Mean"   = mean,
#                       "IQR"    = IQR
#                     ) |> pander::pander()
```

--------------------------------------------------------------------------
           Variables                N        %       Med    Mean     IQR  
-------------------------------- -------- -------- ------- ------- -------
 **During the past 7 days, how    525605   69.46     --      --       1   
 often did you feel so nervous                                            
  that nothing could calm you                                             
          down? (D1)**                                                    

*None of the time*                365108   15.81     --      --       0   

*A little of the time*            83105    11.17     --      --       0   

*Some of the time*                58726    2.439     --      --       0   

 *Most of the time*               12821    1.112     --      --       0   

*All the time*                     5845    525605    --      --       0   

 **During the past 7 days, how    525605    58.6     --      --       1   
     often did you feel so                                                
  depressed that nothing could                                            
      cheer you up? (D2)**                                                

*None of the time*                307998   18.08     --      --       0   

*A little of the time*            95013    16.19     --      --       0   

*Some of the time*                85108    4.899     --      --       0   

*Most of the time*                25752    2.232     --      --       0   

*All the time*                    11734    525605    --      --       0   

     **What is your age?**        525605   3.895     --      --       2   

 *18-24*                          20472    17.35     --      --       0   

 *25-34*                          91190    23.82     --      --       0   

 *35-44*                          125206    22.8     --      --       0   

 *45-54*                          119855   20.25     --      --       0   

 *55-64*                          106413   9.684     --      --       0   

 *65-74*                          50899    2.201     --      --       0   

  *75+*                           11570    525605    --      --       0   

    **What is your gender?**      525605   43.46     --      --       1   

   *Male*                         228404   55.69     --      --       0   

   *Female*                       292686   0.2882    --      --       0   

   *Other*                         1515    0.5708    --      --       0   

   *Prefer not to answer*          3000    525605    --      --       0   

 **What is the highest level of   525605   0.3428    --      --       2   
    education that you have                                               
          completed?**                                                    

 *No formal schooling*             1802    0.7386    --      --       0   

*Less than primary school*         3882    4.302     --      --       0   

*Primary school completed*        22611    32.25     --      --       0   

*Secondary school complete*       169503   31.82     --      --       0   

*High school (or                  167241   20.61     --      --       0   
equivalent) completed*

*College/                         108301   9.944     --      --       0   
   pre-university/ University                                             
           completed*                                                     

*University                       52265    525605    --      --       0   
      post-graduate degree                                                
           completed*                                                     

     **Which of these best        525605   38.64     --      --       2   
  describes the area where you                                            
    are currently staying?**                                              

*City*                            203070   28.27     --      --       0   
                                                      

*Town*                            148583    33.1     --      --       0   

*Village or rural area*           173952   525605    --      --       0
--------------------------------------------------------------------------


--------------------------------------------------------------------------
           Variables                N        %       Med    Mean     IQR  
-------------------------------- -------- -------- ------- ------- -------
**How many people slept in the    525605     --       2     2.555     2   
  place where you stayed last                                             
  night (including yourself)?**                                             

**How many rooms are used for     525605     --       2     1.976     2   
  sleeping in the place where                                             
        you are staying?**                                                  

 **In the past 4 weeks, did you   525605    72.1     --      --       1   
     do any work for pay?**                                               

*Yes*                             378987    27.9     --      --       0   

*No*                              146618   525605    --      --       0   

  **Index (0-100%) for the        525605     --     40.32   35.64   15.82 
    severity of containment                                               
   measures imposed per day:                                              
            General**                                                       

**Index (0-100) for the severity  525605     --     40.6    39.68   39.6  
    of containment measures                                               
 prescribed per day: Secondary                                            
            schools**                                                       

**Index (0-100) for the severity  525605     --     40.6    36.59   19.8  
    of containment measures                                               
 prescribed per day: Elementary                                           
            Schools**                                                       

**Index (0-100) for the severity  525605     --     20.8    29.42   19.8  
    of containment measures                                               
  prescribed per day: Daycare                                             
            centers**                                                       

**Index (0-100) for the severity  525605     --      56     51.16    22   
    of containment measures                                               
    prescribed per day: Mask                                              
           obligation**                                                     
--------------------------------------------------------------------------